models:
  qwen3-vl-2b:
    repo: "Qwen/Qwen3-VL-2B-Instruct"
    max_model_len: 8192
    tensor_parallel_size: 1
    gpu_memory_utilization: 0.8
    num_engines_per_node: 1
    default_max_tokens: 512
    default_temperature: 0.2
  qwen3-vl-4b:
    repo: "Qwen/Qwen3-VL-8B-Instruct"
    max_model_len: 8192
    tensor_parallel_size: 1
    gpu_memory_utilization: 0.8
    num_engines_per_node: 1
    default_max_tokens: 512
    default_temperature: 0.2

